
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 03 20:43:13 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 14;
  public static final int CONST = 6;
  public static final int CHAR = 20;
  public static final int RET = 11;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int FOR = 15;
  public static final int MINUS = 23;
  public static final int STAT = 16;
  public static final int NSPACE = 17;
  public static final int RPAREN = 43;
  public static final int RBOX = 45;
  public static final int LT = 31;
  public static final int COMMA = 40;
  public static final int BOOL = 21;
  public static final int CLASS = 4;
  public static final int INC = 36;
  public static final int BAND = 33;
  public static final int DIV = 25;
  public static final int EXT = 13;
  public static final int GEQ = 30;
  public static final int PLUS = 22;
  public static final int IF = 7;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int LAMBDA = 48;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 19;
  public static final int MOD = 26;
  public static final int NEQ = 28;
  public static final int BREAK = 3;
  public static final int IDENT = 18;
  public static final int VOID = 12;
  public static final int EQ = 35;
  public static final int COLON = 39;
  public static final int LBRACE = 46;
  public static final int BOR = 34;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACE = 47;
  public static final int EQCOMP = 27;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int LBOX = 44;
  public static final int DEC = 37;
  public static final int GT = 29;
  public static final int PRINT = 9;
}

